### PR TITLE
Add linting

### PR DESCRIPTION
**Pull request by gaetanfl**

### CODE REVIEW

**Comment by dzervas** [comment]
Can you rebase on current master (I accepted #1).

All seems good (haven't tested it though) but I'm thinking to name `requiremenets.txt` to something else - maybe `requirements-lint.txt` or `-ci` to be clear that no custom python shenanigans are needed for this role to work.

Very nice job!

**Comment by gaetanfl** [comment]
> Can you rebase on current master (I accepted #1).
> 
Done

> All seems good (haven't tested it though) but I'm thinking to name `requiremenets.txt` to something else - maybe `requirements-lint.txt` or `-ci` to be clear that no custom python shenanigans are needed for this role to work.
>
I suffixed it with tests since I have another PR coming with molecule tests
 
> Very nice job!

Thanks

**Comment by dzervas** [comment]
YEY! Show me the way, I always wanted to use molecule!

Keep it coming!

**Comment by dzervas** [comment]
Just saw `python-version: [3.6, 3.7]`. Why is that? is there any difference between the too, as far as ansible-lint is considered?

**Comment by gaetanfl** [comment]
I was planning to add molecule so I just kind of copy pasted the exemple from molecule. Which can run the linting part
https://molecule.readthedocs.io/en/latest/ci.html#github-actions

**Pull request merged**
